import Foundation

// MARK: - NamuStrings
//
// Centralized localized string constants.
// Each static property is a String(localized:) call site that gets picked up
// by the localization toolchain (genstrings / swift-format-localization).
// Use these instead of inline string literals for new UI code.

// swiftlint:disable file_length type_body_length
enum NamuStrings {

    // MARK: - App

    enum App {
        static let name = String(localized: "app.name", defaultValue: "Namu")
        static let tagline = String(localized: "app.tagline", defaultValue: "Terminal multiplexer for macOS")
        static let ok = String(localized: "app.ok", defaultValue: "OK")
        static let cancel = String(localized: "app.cancel", defaultValue: "Cancel")
        static let save = String(localized: "app.save", defaultValue: "Save")
        static let delete = String(localized: "app.delete", defaultValue: "Delete")
        static let done = String(localized: "app.done", defaultValue: "Done")
        static let close = String(localized: "app.close", defaultValue: "Close")
        static let edit = String(localized: "app.edit", defaultValue: "Edit")
        static let add = String(localized: "app.add", defaultValue: "Add")
        static let remove = String(localized: "app.remove", defaultValue: "Remove")
        static let reset = String(localized: "app.reset", defaultValue: "Reset")
        static let copy = String(localized: "app.copy", defaultValue: "Copy")
        static let paste = String(localized: "app.paste", defaultValue: "Paste")
        static let clear = String(localized: "app.clear", defaultValue: "Clear")
        static let confirm = String(localized: "app.confirm", defaultValue: "Confirm")
        static let apply = String(localized: "app.apply", defaultValue: "Apply")
        static let `continue` = String(localized: "app.continue", defaultValue: "Continue")
        static let back = String(localized: "app.back", defaultValue: "Back")
        static let next = String(localized: "app.next", defaultValue: "Next")
        static let previous = String(localized: "app.previous", defaultValue: "Previous")
        static let open = String(localized: "app.open", defaultValue: "Open")
        static let refresh = String(localized: "app.refresh", defaultValue: "Refresh")
        static let retry = String(localized: "app.retry", defaultValue: "Retry")
        static let loading = String(localized: "app.loading", defaultValue: "Loading…")
        static let error = String(localized: "app.error", defaultValue: "Error")
        static let warning = String(localized: "app.warning", defaultValue: "Warning")
        static let success = String(localized: "app.success", defaultValue: "Success")
        static let notAvailable = String(localized: "app.notAvailable", defaultValue: "Not Available")
        static let unknown = String(localized: "app.unknown", defaultValue: "Unknown")
        static let none = String(localized: "app.none", defaultValue: "None")
        static let all = String(localized: "app.all", defaultValue: "All")
        static let enabled = String(localized: "app.enabled", defaultValue: "Enabled")
        static let disabled = String(localized: "app.disabled", defaultValue: "Disabled")
        static let on = String(localized: "app.on", defaultValue: "On")
        static let off = String(localized: "app.off", defaultValue: "Off")
        static let yes = String(localized: "app.yes", defaultValue: "Yes")
        static let no = String(localized: "app.no", defaultValue: "No")
        static let search = String(localized: "app.search", defaultValue: "Search")
        static let filter = String(localized: "app.filter", defaultValue: "Filter")
        static let sort = String(localized: "app.sort", defaultValue: "Sort")
        static let noResults = String(localized: "app.noResults", defaultValue: "No results")
        static let noItems = String(localized: "app.noItems", defaultValue: "No items")
        static let empty = String(localized: "app.empty", defaultValue: "Empty")
        static let optional = String(localized: "app.optional", defaultValue: "Optional")
        static let required = String(localized: "app.required", defaultValue: "Required")
        static let default_ = String(localized: "app.default", defaultValue: "Default")
        static let custom = String(localized: "app.custom", defaultValue: "Custom")
    }

    // MARK: - Toolbar

    enum Toolbar {
        static let searchPlaceholder = String(localized: "toolbar.search.placeholder", defaultValue: "Search...")
        static let searchTooltip = String(localized: "toolbar.search.tooltip", defaultValue: "Open Command Palette (⌘K)")
        static let searchAccessibility = String(localized: "toolbar.search.accessibility", defaultValue: "Search and command palette")
        static let settingsTooltip = String(localized: "toolbar.settings.tooltip", defaultValue: "Open Settings")
        static let settingsAccessibility = String(localized: "toolbar.settings.accessibility", defaultValue: "Settings")
        static let newWindowTooltip = String(localized: "toolbar.newWindow.tooltip", defaultValue: "New Window")
        static let newWindowAccessibility = String(localized: "toolbar.newWindow.accessibility", defaultValue: "New Window")
    }

    // MARK: - Sidebar

    enum Sidebar {
        static let title = String(localized: "sidebar.title", defaultValue: "Workspaces")
        static let newWorkspaceTitle = String(localized: "sidebar.newWorkspace.title", defaultValue: "New Workspace")
        static let newWorkspaceTooltip = String(localized: "sidebar.newWorkspace.tooltip", defaultValue: "Create a new workspace")
        static let renameTitle = String(localized: "sidebar.rename.title", defaultValue: "Rename Workspace")
        static let renamePlaceholder = String(localized: "sidebar.rename.placeholder", defaultValue: "Workspace name")
        static let renameCancelTooltip = String(localized: "sidebar.rename.cancel.tooltip", defaultValue: "Cancel rename")
        static let notificationsTooltip = String(localized: "sidebar.notifications.tooltip", defaultValue: "Notifications (⌘⇧I)")
        static let notificationsLabel = String(localized: "sidebar.notifications.label", defaultValue: "Notifications")
        static let notificationsHint = String(localized: "sidebar.notifications.hint", defaultValue: "Toggle the notifications panel")
        static let settingsTitle = String(localized: "settings.title", defaultValue: "Settings")
        static let addButtonTitle = String(localized: "sidebar.addButton.title", defaultValue: "New Workspace")
        static let addButtonTooltip = String(localized: "sidebar.addButton.tooltip", defaultValue: "Create a new workspace (⌘N)")
        static let addButtonAccessibility = String(localized: "sidebar.addButton.accessibility", defaultValue: "New Workspace")
        static let addButtonHint = String(localized: "sidebar.addButton.hint", defaultValue: "Creates a new terminal workspace")
        static let windowLabel = String(localized: "sidebar.window.label", defaultValue: "Window 2")
    }

    // MARK: - Sidebar Item

    enum SidebarItem {
        static let remoteLabel = String(localized: "sidebar.item.remote.label", defaultValue: "Remote")
        static let menuRename = String(localized: "sidebar.item.menu.rename", defaultValue: "Rename")
        static let menuPin = String(localized: "sidebar.item.menu.pin", defaultValue: "Pin")
        static let menuUnpin = String(localized: "sidebar.item.menu.unpin", defaultValue: "Unpin")
        static let menuSetColor = String(localized: "sidebar.item.menu.setColor", defaultValue: "Set Color")
        static let menuClearColor = String(localized: "sidebar.item.color.clear", defaultValue: "Clear Color")
        static let menuMoveToWindow = String(localized: "sidebar.item.menu.moveToWindow", defaultValue: "Move to Window")
        static let menuCloseWorkspace = String(localized: "sidebar.item.menu.closeWorkspace", defaultValue: "Close Workspace")
        static let closeTooltip = String(localized: "sidebar.item.close.tooltip", defaultValue: "Close Workspace")
        static let closeAccessibility = String(localized: "sidebar.item.close.accessibility", defaultValue: "Close Workspace")
        static let pinnedAccessibility = String(localized: "sidebar.item.pinned.accessibility", defaultValue: "Pinned")
        static let prStateOpen = String(localized: "sidebar.pr.state.open", defaultValue: "open")
        static let prStateMerged = String(localized: "sidebar.pr.state.merged", defaultValue: "merged")
        static let prStateClosed = String(localized: "sidebar.pr.state.closed", defaultValue: "closed")
        static func unreadBadge(count: Int) -> String {
            String(format: String(localized: "sidebar.item.unreadBadge.accessibility", defaultValue: "%d unread notifications"), count)
        }
    }

    // MARK: - Workspace

    enum Workspace {
        static let defaultTitle = String(localized: "workspace.defaultTitle", defaultValue: "Workspace")
        static let defaultTabTerminal = String(localized: "workspace.defaultTab.terminal", defaultValue: "Terminal")
        static let emptyTitle = String(localized: "workspace.empty.title", defaultValue: "No workspace selected")
        static let emptyMessage = String(localized: "workspace.empty.message", defaultValue: "Create a workspace to get started")
        static let createFirst = String(localized: "workspace.createFirst", defaultValue: "Create your first workspace")
        static let deleteTitle = String(localized: "workspace.delete.title", defaultValue: "Delete Workspace")
        static let deleteMessage = String(localized: "workspace.delete.message", defaultValue: "Are you sure you want to delete this workspace? This cannot be undone.")
        static let deleteConfirm = String(localized: "workspace.delete.confirm", defaultValue: "Delete")
        static let closeConfirm = String(localized: "workspace.close.confirm", defaultValue: "Close")
        static let closeMessage = String(localized: "workspace.close.message", defaultValue: "Close this workspace?")
        static let newTitle = String(localized: "workspace.new.title", defaultValue: "New Workspace")
        static let renameTitle = String(localized: "workspace.rename.title", defaultValue: "Rename")
        static let renamePrompt = String(localized: "workspace.rename.prompt", defaultValue: "Enter new workspace name")
        static let colorPickerTitle = String(localized: "workspace.colorPicker.title", defaultValue: "Choose Color")
        static let splitHorizontal = String(localized: "workspace.split.horizontal", defaultValue: "Split Horizontally")
        static let splitVertical = String(localized: "workspace.split.vertical", defaultValue: "Split Vertically")
        static let focusNext = String(localized: "workspace.focus.next", defaultValue: "Focus Next Pane")
        static let focusPrevious = String(localized: "workspace.focus.previous", defaultValue: "Focus Previous Pane")
        static let zoomPane = String(localized: "workspace.zoom.pane", defaultValue: "Zoom Pane")
        static let unzoomPane = String(localized: "workspace.unzoom.pane", defaultValue: "Unzoom Pane")
    }

    // MARK: - Terminal

    enum Terminal {
        static let title = String(localized: "terminal.title", defaultValue: "Terminal")
        static let newTab = String(localized: "terminal.newTab", defaultValue: "New Tab")
        static let closeTab = String(localized: "terminal.closeTab", defaultValue: "Close Tab")
        static let renameTab = String(localized: "terminal.renameTab", defaultValue: "Rename Tab")
        static let copyMode = String(localized: "terminal.copyMode", defaultValue: "Copy Mode")
        static let exitCopyMode = String(localized: "terminal.exitCopyMode", defaultValue: "Exit Copy Mode")
        static let scrollUp = String(localized: "terminal.scrollUp", defaultValue: "Scroll Up")
        static let scrollDown = String(localized: "terminal.scrollDown", defaultValue: "Scroll Down")
        static let clearScreen = String(localized: "terminal.clearScreen", defaultValue: "Clear Screen")
        static let searchTitle = String(localized: "terminal.search.title", defaultValue: "Find in Terminal")
        static let searchPlaceholder = String(localized: "find.placeholder", defaultValue: "Find in terminal...")
        static let searchNextTooltip = String(localized: "find.nextMatch.tooltip", defaultValue: "Next match (Enter)")
        static let searchPreviousTooltip = String(localized: "find.previousMatch.tooltip", defaultValue: "Previous match (Shift+Enter)")
        static let searchCloseTooltip = String(localized: "find.close.tooltip", defaultValue: "Close (Esc)")
        static let searchNextAccessibility = String(localized: "terminal.search.next.accessibility", defaultValue: "Next match")
        static let searchPreviousAccessibility = String(localized: "terminal.search.previous.accessibility", defaultValue: "Previous match")
        static let searchCloseAccessibility = String(localized: "terminal.search.close.accessibility", defaultValue: "Close search")
        static let noMatchesFound = String(localized: "terminal.search.noMatches", defaultValue: "No matches found")
        static let matchCountFormat = String(localized: "terminal.search.matchCount", defaultValue: "Match %d of %d")
        static let fontSizeIncrease = String(localized: "terminal.fontSize.increase", defaultValue: "Increase Font Size")
        static let fontSizeDecrease = String(localized: "terminal.fontSize.decrease", defaultValue: "Decrease Font Size")
        static let fontSizeReset = String(localized: "terminal.fontSize.reset", defaultValue: "Reset Font Size")
    }

    // MARK: - Browser

    enum Browser {
        static let title = String(localized: "browser.title", defaultValue: "Browser")
        static let newTab = String(localized: "browser.newTab", defaultValue: "New Tab")
        static let closeTab = String(localized: "browser.closeTab", defaultValue: "Close Tab")
        static let urlbarPlaceholder = String(localized: "browser.urlbar.placeholder", defaultValue: "Enter URL...")
        static let backTooltip = String(localized: "browser.back.tooltip", defaultValue: "Back")
        static let backAccessibility = String(localized: "browser.back.accessibility", defaultValue: "Go Back")
        static let forwardTooltip = String(localized: "browser.forward.tooltip", defaultValue: "Forward")
        static let forwardAccessibility = String(localized: "browser.forward.accessibility", defaultValue: "Go Forward")
        static let reloadTooltip = String(localized: "browser.reload.tooltip", defaultValue: "Reload")
        static let reloadAccessibility = String(localized: "browser.reload.accessibility", defaultValue: "Reload Page")
        static let stopTooltip = String(localized: "browser.stop.tooltip", defaultValue: "Stop")
        static let stopAccessibility = String(localized: "browser.stop.accessibility", defaultValue: "Stop Loading")
        static let findTooltip = String(localized: "browser.findInPage.tooltip", defaultValue: "Find in Page")
        static let findAccessibility = String(localized: "browser.findInPage.accessibility", defaultValue: "Find in Page")
        static let findPlaceholder = String(localized: "browser.findInPage.fieldPlaceholder", defaultValue: "Find in page")
        static let findNoResults = String(localized: "browser.findInPage.noResults", defaultValue: "No results")
        static let findPreviousTooltip = String(localized: "browser.findInPage.previous.tooltip", defaultValue: "Previous match (⌘⇧G)")
        static let findPreviousAccessibility = String(localized: "browser.findInPage.previous.accessibility", defaultValue: "Previous match")
        static let findNextTooltip = String(localized: "browser.findInPage.next.tooltip", defaultValue: "Next match (⌘G)")
        static let findNextAccessibility = String(localized: "browser.findInPage.next.accessibility", defaultValue: "Next match")
        static let findCloseTooltip = String(localized: "browser.findInPage.close.tooltip", defaultValue: "Close find bar (Esc)")
        static let findCloseAccessibility = String(localized: "browser.findInPage.close.accessibility", defaultValue: "Close")
        static let devToolsTitle = String(localized: "browser.devTools.title", defaultValue: "Developer Tools")
        static let consoleTitle = String(localized: "browser.console.title", defaultValue: "Console")
        static let historyTitle = String(localized: "browser.history.title", defaultValue: "History")
        static let bookmarksTitle = String(localized: "browser.bookmarks.title", defaultValue: "Bookmarks")
        static let downloadsTitle = String(localized: "browser.downloads.title", defaultValue: "Downloads")
        static let loadingMessage = String(localized: "browser.loading.message", defaultValue: "Loading…")
        static let errorTitle = String(localized: "browser.error.title", defaultValue: "Page Not Found")
        static let errorMessage = String(localized: "browser.error.message", defaultValue: "The page could not be loaded.")
        static let noWebView = String(localized: "browser.noWebView", defaultValue: "No web view")
        static let profileDefault = String(localized: "browser.profile.default", defaultValue: "Default Profile")
        static let profileNew = String(localized: "browser.profile.new", defaultValue: "New Profile")
        static let profileDelete = String(localized: "browser.profile.delete", defaultValue: "Delete Profile")
        static let profileRename = String(localized: "browser.profile.rename", defaultValue: "Rename Profile")
        static let searchEngineGoogle = String(localized: "browser.searchEngine.google", defaultValue: "Google")
        static let searchEngineDuckDuckGo = String(localized: "browser.searchEngine.duckduckgo", defaultValue: "DuckDuckGo")
        static let searchEngineBing = String(localized: "browser.searchEngine.bing", defaultValue: "Bing")
        static let zoomIn = String(localized: "browser.zoom.in", defaultValue: "Zoom In")
        static let zoomOut = String(localized: "browser.zoom.out", defaultValue: "Zoom Out")
        static let zoomReset = String(localized: "browser.zoom.reset", defaultValue: "Reset Zoom")
        static let printPage = String(localized: "browser.print", defaultValue: "Print Page")
        static let savePage = String(localized: "browser.savePage", defaultValue: "Save Page")
        static let viewSource = String(localized: "browser.viewSource", defaultValue: "View Source")
        static let copyURL = String(localized: "browser.copyURL", defaultValue: "Copy URL")
        static let openInSafari = String(localized: "browser.openInSafari", defaultValue: "Open in Safari")
    }

    // MARK: - Notifications

    enum Notifications {
        static let title = String(localized: "notifications.title", defaultValue: "Notifications")
        static let emptyTitle = String(localized: "notifications.empty.title", defaultValue: "No notifications yet")
        static let emptyMessage = String(localized: "notifications.empty.message", defaultValue: "Notifications from your workspaces will appear here")
        static let clearAll = String(localized: "notifications.clearAll", defaultValue: "Clear All")
        static let jumpToLatest = String(localized: "notifications.jumpToLatestUnread", defaultValue: "Jump to Latest Unread")
        static let markAllRead = String(localized: "notifications.markAllRead", defaultValue: "Mark All Read")
        static let markRead = String(localized: "notifications.markRead", defaultValue: "Mark as Read")
        static let markUnread = String(localized: "notifications.markUnread", defaultValue: "Mark as Unread")
        static let deleteNotification = String(localized: "notifications.delete", defaultValue: "Delete")
        static let rowRemoveTooltip = String(localized: "notifications.row.remove.tooltip", defaultValue: "Remove notification")
        static let rowRemoveAccessibility = String(localized: "notifications.row.remove.accessibility", defaultValue: "Remove notification")
        static let rowOpenAccessibility = String(localized: "notifications.row.open.accessibility", defaultValue: "Open notification")
        static let rowUnreadAccessibility = String(localized: "notifications.row.unread.accessibility", defaultValue: "Unread")
        static let bellTooltip = String(localized: "notifications.bell.tooltip", defaultValue: "Notifications")
        static let bellAccessibility = String(localized: "notifications.bell.accessibility", defaultValue: "Notifications")
        static let filterAll = String(localized: "notifications.filter.all", defaultValue: "All")
        static let filterUnread = String(localized: "notifications.filter.unread", defaultValue: "Unread")
        static let filterRead = String(localized: "notifications.filter.read", defaultValue: "Read")
        static let typeInfo = String(localized: "notifications.type.info", defaultValue: "Info")
        static let typeWarning = String(localized: "notifications.type.warning", defaultValue: "Warning")
        static let typeError = String(localized: "notifications.type.error", defaultValue: "Error")
        static let typeSuccess = String(localized: "notifications.type.success", defaultValue: "Success")
        static let timeJustNow = String(localized: "notifications.time.justNow", defaultValue: "Just now")
        static let timeAgo = String(localized: "notifications.time.ago", defaultValue: "ago")
    }

    // MARK: - Settings

    enum Settings {
        static let title = String(localized: "settings.title", defaultValue: "Settings")
        static let sectionGeneral = String(localized: "settings.section.general", defaultValue: "General")
        static let sectionAppearance = String(localized: "settings.section.appearance", defaultValue: "Appearance")
        static let sectionColors = String(localized: "settings.section.colors", defaultValue: "Workspace Colors")
        static let sectionAI = String(localized: "settings.section.ai", defaultValue: "AI Providers")
        static let sectionKeyboard = String(localized: "settings.section.keyboard", defaultValue: "Keyboard")
        static let sectionUpdates = String(localized: "settings.section.updates", defaultValue: "Updates")
        static let generalTitle = String(localized: "settings.general.title", defaultValue: "General")
        static let generalSubtitle = String(localized: "settings.general.subtitle", defaultValue: "Appearance and behavior settings")
        static let generalVersionLabel = String(localized: "settings.general.version.label", defaultValue: "Version")
        static let generalStartupTitle = String(localized: "settings.general.startup.title", defaultValue: "Startup")
        static let generalStartupRestoreLabel = String(localized: "settings.general.startup.restore.label", defaultValue: "Restore workspaces on launch")
        static let generalStartupNewWorkspaceLabel = String(localized: "settings.general.startup.newWorkspace.label", defaultValue: "Open new workspace on launch")
        static let generalConfirmCloseLabel = String(localized: "settings.general.confirmClose.label", defaultValue: "Confirm before closing workspace")
        static let generalConfirmCloseDescription = String(localized: "settings.general.confirmClose.description", defaultValue: "Show a confirmation dialog when closing a workspace with running processes")
        static let generalScrollbackLabel = String(localized: "settings.general.scrollback.label", defaultValue: "Scrollback lines")
        static let generalScrollbackDescription = String(localized: "settings.general.scrollback.description", defaultValue: "Number of lines to keep in terminal scrollback buffer")
        static let generalBellLabel = String(localized: "settings.general.bell.label", defaultValue: "Terminal bell")
        static let generalBellDescription = String(localized: "settings.general.bell.description", defaultValue: "Play a sound when the terminal bell rings")
        static let generalCursorBlinkLabel = String(localized: "settings.general.cursorBlink.label", defaultValue: "Blink cursor")
        static let generalCursorStyleLabel = String(localized: "settings.general.cursorStyle.label", defaultValue: "Cursor style")
        static let generalCursorBlock = String(localized: "settings.general.cursor.block", defaultValue: "Block")
        static let generalCursorBar = String(localized: "settings.general.cursor.bar", defaultValue: "Bar")
        static let generalCursorUnderline = String(localized: "settings.general.cursor.underline", defaultValue: "Underline")
        static let appearanceTitle = String(localized: "settings.appearance.title", defaultValue: "Appearance")
        static let appearanceSubtitle = String(localized: "settings.appearance.subtitle", defaultValue: "Customize the look and feel of Namu")
        static let appearanceThemeLabel = String(localized: "settings.appearance.theme.label", defaultValue: "Theme")
        static let appearanceLightFrom = String(localized: "settings.appearance.theme.lightFrom", defaultValue: "Light mode from")
        static let appearanceDarkFrom = String(localized: "settings.appearance.theme.darkFrom", defaultValue: "Dark mode from")
        static let appearanceSidebarLabel = String(localized: "settings.appearance.sidebar.label", defaultValue: "Sidebar")
        static let appearanceSidebarMaterial = String(localized: "settings.appearance.sidebar.material", defaultValue: "Material")
        static let appearanceSidebarTintColor = String(localized: "settings.appearance.sidebar.tintColor", defaultValue: "Tint Color")
        static let appearanceSidebarOpacity = String(localized: "settings.appearance.sidebar.opacity", defaultValue: "Opacity")
        static let appearanceSidebarTintNote = String(localized: "settings.appearance.sidebar.tintNote", defaultValue: "Tint overlays the sidebar background material.")
        static let appearanceWindowOpacityLabel = String(localized: "settings.appearance.windowOpacity.label", defaultValue: "Window Opacity")
        static let appearanceWindowOpacityNote = String(localized: "settings.appearance.windowOpacity.note", defaultValue: "Lower opacity can help when referencing other windows.")
        static let appearanceFontLabel = String(localized: "settings.appearance.font.label", defaultValue: "Terminal Font")
        static let appearanceFontFamily = String(localized: "settings.appearance.font.family", defaultValue: "Family")
        static let appearanceFontFamilyPlaceholder = String(localized: "settings.appearance.font.familyPlaceholder", defaultValue: "Default (system mono)")
        static let appearanceFontSize = String(localized: "settings.appearance.font.size", defaultValue: "Size")
        static let appearanceFontLineHeight = String(localized: "settings.appearance.font.lineHeight", defaultValue: "Line Height")
        static let appearanceFontSpacing = String(localized: "settings.appearance.font.spacing", defaultValue: "Spacing")
        static let appearanceFontNote = String(localized: "settings.appearance.font.note", defaultValue: "Font changes apply to new terminal sessions.")
        static let colorsTitle = String(localized: "settings.colors.title", defaultValue: "Workspace Colors")
        static let colorsSubtitle = String(localized: "settings.colors.subtitle", defaultValue: "Customize the accent colors available for workspaces.")
        static let colorsPaletteLabel = String(localized: "settings.colors.palette.label", defaultValue: "Color Palette")
        static let colorsHexPlaceholder = String(localized: "settings.colors.hexInput.placeholder", defaultValue: "#RRGGBB")
        static let colorsAddButton = String(localized: "settings.colors.addButton", defaultValue: "Add")
        static let colorsHexError = String(localized: "settings.colors.hexError", defaultValue: "Invalid hex color")
        static let colorsResetButton = String(localized: "settings.colors.resetButton", defaultValue: "Reset to Defaults")
        static let colorsSwatchTooltip = String(localized: "settings.colors.swatch.tooltip", defaultValue: "Select color")
        static let colorsSwatchRemoveTooltip = String(localized: "settings.colors.swatch.remove.tooltip", defaultValue: "Remove custom color")
        static let colorsSwatchRemoveAccessibility = String(localized: "settings.colors.swatch.remove.accessibility", defaultValue: "Remove this color from palette")
        static let aiTitle = String(localized: "settings.ai.title", defaultValue: "AI Providers")
        static let aiSubtitle = String(localized: "settings.ai.subtitle", defaultValue: "Configure API keys for each provider. Enable the ones you want to use.")
        static let aiStatusReady = String(localized: "settings.ai.status.ready", defaultValue: "Ready")
        static let aiStatusNeedsKey = String(localized: "settings.ai.status.needsKey", defaultValue: "Needs key")
        static let aiCustomBaseURLPlaceholder = String(localized: "settings.ai.customBaseURL.placeholder", defaultValue: "Base URL")
        static let aiModelsLabel = String(localized: "settings.ai.modelsLabel", defaultValue: "Models:")
        static let keyboardTitle = String(localized: "settings.keyboard.title", defaultValue: "Keyboard Shortcuts")
        static let keyboardSubtitle = String(localized: "settings.keyboard.subtitle", defaultValue: "Customize keyboard shortcuts for all actions")
        static let keyboardRestoreDefaults = String(localized: "keyboard.restoreDefaults.button", defaultValue: "Restore Defaults")
        static let keyboardConflictDismiss = String(localized: "keyboard.conflict.dismiss", defaultValue: "Dismiss")
        static let keyboardRecorderPress = String(localized: "keyboard.recorder.pressShortcut", defaultValue: "Press shortcut…")
        static let updatesTitle = String(localized: "settings.updates.title", defaultValue: "Updates")
        static let updatesSubtitle = String(localized: "settings.updates.subtitle", defaultValue: "Keep Namu up to date")
        static let updatesCurrentVersionLabel = String(localized: "settings.updates.currentVersion.label", defaultValue: "Current Version")
        static let updatesAutomaticLabel = String(localized: "settings.updates.automatic.label", defaultValue: "Automatic updates")
        static let updatesAutomaticDescription = String(localized: "settings.updates.automatic.description", defaultValue: "Automatically check for updates in the background")
        static let updatesCheckButton = String(localized: "settings.updates.checkButton", defaultValue: "Check for Updates")
        static let updatesCheckButtonChecking = String(localized: "settings.updates.checkButton.checking", defaultValue: "Checking...")
        static let updatesSparkleNote = String(localized: "settings.updates.sparkleNote", defaultValue: "Sparkle auto-update integration will be available in the distributed release.")
    }

    // MARK: - Command Palette

    enum CommandPalette {
        static let placeholder = String(localized: "commandPalette.placeholder", defaultValue: "Search commands…")
        static let noResults = String(localized: "commandPalette.noResults", defaultValue: "No matching commands")
        static let recentTitle = String(localized: "commandPalette.recent.title", defaultValue: "Recent")
        static let allTitle = String(localized: "commandPalette.all.title", defaultValue: "All Commands")
        static let cmdNewWorkspace = String(localized: "commandPalette.cmd.newWorkspace", defaultValue: "New Workspace")
        static let cmdCloseWorkspace = String(localized: "commandPalette.cmd.closeWorkspace", defaultValue: "Close Workspace")
        static let cmdSplitHorizontal = String(localized: "commandPalette.cmd.splitHorizontal", defaultValue: "Split Horizontal")
        static let cmdSplitVertical = String(localized: "commandPalette.cmd.splitVertical", defaultValue: "Split Vertical")
        static let cmdToggleSidebar = String(localized: "commandPalette.cmd.toggleSidebar", defaultValue: "Toggle Sidebar")
        static let cmdToggleFind = String(localized: "commandPalette.cmd.toggleFind", defaultValue: "Toggle Find")
        static let cmdOpenSettings = String(localized: "commandPalette.cmd.openSettings", defaultValue: "Open Settings")
        static let cmdToggleAIChat = String(localized: "commandPalette.cmd.toggleAIChat", defaultValue: "Toggle AI Chat")
        static let cmdFocusNext = String(localized: "commandPalette.cmd.focusNext", defaultValue: "Focus Next Pane")
        static let cmdFocusPrev = String(localized: "commandPalette.cmd.focusPrev", defaultValue: "Focus Previous Pane")
        static let cmdZoomPane = String(localized: "commandPalette.cmd.zoomPane", defaultValue: "Zoom Focused Pane")
        static let cmdMinimalMode = String(localized: "commandPalette.cmd.minimalMode", defaultValue: "Toggle Minimal Mode")
    }

    // MARK: - AI Chat

    enum AIChat {
        static let headerTitle = String(localized: "ai.header.title", defaultValue: "Namu AI")
        static let setupTitle = String(localized: "ai.setup.title", defaultValue: "Namu AI")
        static let setupBody = String(localized: "ai.setup.body", defaultValue: "Configure your AI provider in Settings to get started.")
        static let setupOpenSettings = String(localized: "ai.setup.openSettings", defaultValue: "Open Settings")
        static let processingThinking = String(localized: "ai.processing.thinking", defaultValue: "Thinking...")
        static let chatPlaceholder = String(localized: "ai.chat.placeholder", defaultValue: "Ask Namu AI...")
        static let sendAccessibility = String(localized: "ai.chat.send.accessibility", defaultValue: "Send message")
        static let clearConversation = String(localized: "ai.chat.clear", defaultValue: "Clear Conversation")
        static let newConversation = String(localized: "ai.chat.new", defaultValue: "New Conversation")
        static let copyResponse = String(localized: "ai.chat.copy", defaultValue: "Copy Response")
        static let errorTitle = String(localized: "ai.error.title", defaultValue: "AI Error")
        static let errorNoProvider = String(localized: "ai.error.noProvider", defaultValue: "No AI provider configured")
        static let errorAuthFailed = String(localized: "ai.error.authFailed", defaultValue: "Authentication failed. Check your API key.")
        static let errorRateLimit = String(localized: "ai.error.rateLimit", defaultValue: "Rate limit reached. Please wait before sending another message.")
        static let errorTimeout = String(localized: "ai.error.timeout", defaultValue: "Request timed out. Please try again.")
        static let errorUnavailable = String(localized: "ai.error.unavailable", defaultValue: "AI temporarily unavailable. Please try again later.")
        static let providerPickerLabel = String(localized: "ai.providerPicker.label", defaultValue: "Provider")
        static let modelPickerLabel = String(localized: "ai.modelPicker.label", defaultValue: "Model")
        static let userRole = String(localized: "ai.message.role.user", defaultValue: "You")
        static let assistantRole = String(localized: "ai.message.role.assistant", defaultValue: "Namu AI")
    }

    // MARK: - AI Preferences

    enum AIPreferences {
        static let providerAnthropic = String(localized: "ai.provider.anthropic", defaultValue: "Anthropic")
        static let providerOpenAI = String(localized: "ai.provider.openai", defaultValue: "OpenAI")
        static let providerOpenRouter = String(localized: "ai.provider.openrouter", defaultValue: "OpenRouter")
        static let safetyLow = String(localized: "ai.safety.level.low", defaultValue: "Low")
        static let safetyMedium = String(localized: "ai.safety.level.medium", defaultValue: "Medium (Recommended)")
        static let safetyHigh = String(localized: "ai.safety.level.high", defaultValue: "High")
        static let safetyLowDescription = String(localized: "ai.safety.level.low.description", defaultValue: "Minimal filtering. Allow all commands.")
        static let safetyMediumDescription = String(localized: "ai.safety.level.medium.description", defaultValue: "Block destructive commands. Confirm risky operations.")
        static let safetyHighDescription = String(localized: "ai.safety.level.high.description", defaultValue: "Strict allowlist. Approve every command before execution.")
        static let tabGeneral = String(localized: "ai.prefs.tab.general", defaultValue: "General")
        static let tabGateway = String(localized: "ai.prefs.tab.gateway", defaultValue: "Gateway")
        static let tabAlertRules = String(localized: "ai.prefs.tab.alertRules", defaultValue: "Alert Rules")
        static let tabPicker = String(localized: "ai.prefs.tab.picker", defaultValue: "Tab")
        static let sectionProvider = String(localized: "ai.prefs.section.provider", defaultValue: "Provider")
        static let sectionAPIKey = String(localized: "ai.prefs.section.apiKey", defaultValue: "API Key")
        static let sectionSafetyLevel = String(localized: "ai.prefs.section.safetyLevel", defaultValue: "Safety Level")
        static let sectionAdvanced = String(localized: "ai.prefs.section.advanced", defaultValue: "Advanced")
        static let sectionGatewayConnection = String(localized: "ai.prefs.section.gatewayConnection", defaultValue: "Gateway Connection")
        static let sectionPairingToken = String(localized: "ai.prefs.section.pairingToken", defaultValue: "Pairing Token")
        static let sectionLinkTelegram = String(localized: "ai.prefs.section.linkTelegram", defaultValue: "Link Telegram")
        static let sectionUnlink = String(localized: "ai.prefs.section.unlink", defaultValue: "Unlink")
        static let apiKeyPlaceholder = String(localized: "ai.prefs.apiKey.placeholder", defaultValue: "Paste API key…")
        static let apiKeyHide = String(localized: "ai.prefs.apiKey.hide", defaultValue: "Hide key")
        static let apiKeyShow = String(localized: "ai.prefs.apiKey.show", defaultValue: "Show key")
        static let apiKeySaveButton = String(localized: "ai.prefs.apiKey.saveButton", defaultValue: "Save Key")
        static let apiKeyTestButton = String(localized: "ai.prefs.apiKey.testButton", defaultValue: "Test Connection")
        static let apiKeyStoredInKeychain = String(localized: "ai.prefs.apiKey.storedInKeychain", defaultValue: "Key stored in Keychain")
        static let providerPicker = String(localized: "ai.prefs.provider.picker", defaultValue: "Provider")
        static let modelPicker = String(localized: "ai.prefs.model.picker", defaultValue: "Model")
        static let safetyPicker = String(localized: "ai.prefs.safety.picker", defaultValue: "Safety")
        static let advancedStreamResponses = String(localized: "ai.prefs.advanced.streamResponses", defaultValue: "Stream responses")
        static let advancedMaxTokens = String(localized: "ai.prefs.advanced.maxTokens", defaultValue: "Max tokens")
        static let saveSettings = String(localized: "ai.prefs.saveSettings.button", defaultValue: "Save Settings")
        static let gatewayURLLabel = String(localized: "ai.prefs.gateway.urlLabel", defaultValue: "URL")
        static let gatewayCheckButton = String(localized: "ai.prefs.gateway.checkButton", defaultValue: "Check Connection")
        static let gatewayConnected = String(localized: "ai.prefs.gateway.connected", defaultValue: "Connected")
        static let connectionConnected = String(localized: "ai.prefs.connection.connected", defaultValue: "Connected")
        static let pairingTokenPlaceholder = String(localized: "ai.prefs.pairingToken.placeholder", defaultValue: "No token generated")
        static let pairingTokenHide = String(localized: "ai.prefs.token.hide", defaultValue: "Hide token")
        static let pairingTokenShow = String(localized: "ai.prefs.token.show", defaultValue: "Show token")
        static let pairingTokenGenerate = String(localized: "ai.prefs.pairingToken.generateButton", defaultValue: "Generate Pairing Token")
        static let pairingTokenCopy = String(localized: "ai.prefs.pairingToken.copyButton", defaultValue: "Copy")
        static let pairingTokenSaved = String(localized: "ai.prefs.pairingToken.savedLabel", defaultValue: "Token saved to preferences")
        static let telegramHowTo = String(localized: "ai.prefs.telegram.howTo", defaultValue: "How to link your Telegram account:")
        static let telegramStep1 = String(localized: "ai.prefs.telegram.step1", defaultValue: "1. Start the Namu Gateway with your Telegram bot token")
        static let telegramStep2 = String(localized: "ai.prefs.telegram.step2", defaultValue: "2. Send /start to your Telegram bot")
        static let telegramStep3 = String(localized: "ai.prefs.telegram.step3", defaultValue: "3. The bot sends you a 6-digit pairing code (valid 5 min)")
        static let telegramStep4 = String(localized: "ai.prefs.telegram.step4", defaultValue: "4. Generate a pairing token above (or use existing)")
        static let telegramStep6 = String(localized: "ai.prefs.telegram.step6", defaultValue: "6. Your Telegram is now linked — send commands via the bot")
        static let telegramQuickLink = String(localized: "ai.prefs.telegram.quickLinkLabel", defaultValue: "Quick link command:")
        static let unlinkDescription = String(localized: "ai.prefs.unlink.description", defaultValue: "To unlink your Telegram account, send /unlink to the bot. This removes the connection between your Telegram chat and Namu.")
    }

    // MARK: - Alert Rules

    enum AlertRules {
        static let newRuleDefaultName = String(localized: "ai.alert.newRule.defaultName", defaultValue: "New Rule")
        static let addRuleButton = String(localized: "ai.alert.addRule.button", defaultValue: "Add Rule")
        static let saveRulesButton = String(localized: "ai.alert.saveRules.button", defaultValue: "Save Rules")
        static let triggerTypeProcessExit = String(localized: "ai.alert.triggerType.processExit", defaultValue: "Process Exit")
        static let triggerTypeOutputMatch = String(localized: "ai.alert.triggerType.outputMatch", defaultValue: "Output Match")
        static let triggerTypePortChange = String(localized: "ai.alert.triggerType.portChange", defaultValue: "Port Change")
        static let triggerTypeShellIdle = String(localized: "ai.alert.triggerType.shellIdle", defaultValue: "Shell Idle")
        static let editRuleTitle = String(localized: "ai.alert.editRule.title", defaultValue: "Edit Alert Rule")
        static let editRuleSectionRule = String(localized: "ai.alert.editRule.section.rule", defaultValue: "Rule")
        static let editRuleSectionTrigger = String(localized: "ai.alert.editRule.section.trigger", defaultValue: "Trigger")
        static let editRuleNamePlaceholder = String(localized: "ai.alert.editRule.namePlaceholder", defaultValue: "Name")
        static let editRuleEnabledToggle = String(localized: "ai.alert.editRule.enabledToggle", defaultValue: "Enabled")
        static let editRuleTypePicker = String(localized: "ai.alert.editRule.typePicker", defaultValue: "Type")
        static let editRuleMatchAnyExit = String(localized: "ai.alert.editRule.matchAnyExit", defaultValue: "Match any exit code")
        static let editRuleExitCodePlaceholder = String(localized: "ai.alert.editRule.exitCodePlaceholder", defaultValue: "Exit code")
        static let editRulePatternPlaceholder = String(localized: "ai.alert.editRule.patternPlaceholder", defaultValue: "Pattern")
        static let editRuleCaseSensitive = String(localized: "ai.alert.editRule.caseSensitive", defaultValue: "Case sensitive")
        static let editRulePortsPlaceholder = String(localized: "ai.alert.editRule.portsPlaceholder", defaultValue: "Ports (comma-separated)")
        static let editRuleIdleSecondsPlaceholder = String(localized: "ai.alert.editRule.idleSecondsPlaceholder", defaultValue: "Idle seconds")
        static let editRuleCancelButton = String(localized: "ai.alert.editRule.cancelButton", defaultValue: "Cancel")
        static let editRuleSaveButton = String(localized: "ai.alert.editRule.saveButton", defaultValue: "Save")
        static let triggerAnyExit = String(localized: "ai.alert.trigger.anyExit", defaultValue: "Any exit")
    }

    // MARK: - Update

    enum Update {
        static let statusChecking = String(localized: "update.status.checking", defaultValue: "Checking for Updates…")
        static let statusUpToDate = String(localized: "update.status.upToDate", defaultValue: "Up to Date")
        static let statusInstalling = String(localized: "update.status.installing", defaultValue: "Installing…")
        static let statusFailed = String(localized: "update.status.failed", defaultValue: "Update Failed")
        static let pillTooltip = String(localized: "update.pill.tooltip", defaultValue: "Update status")
        static let pillAccessibility = String(localized: "update.pill.accessibility", defaultValue: "Update status indicator")
        static let installButton = String(localized: "update.install.button", defaultValue: "Install Update")
        static let dismissButton = String(localized: "update.dismiss.button", defaultValue: "Dismiss")
        static let releaseNotesTitle = String(localized: "update.releaseNotes.title", defaultValue: "Release Notes")
        static let downloadProgress = String(localized: "update.download.progress", defaultValue: "Downloading update…")
        static let restartRequired = String(localized: "update.restart.required", defaultValue: "Restart required to complete update")
        static let restartNow = String(localized: "update.restart.now", defaultValue: "Restart Now")
        static let remindLater = String(localized: "update.remind.later", defaultValue: "Remind Me Later")
        static let skipVersion = String(localized: "update.skip.version", defaultValue: "Skip This Version")
    }

    // MARK: - Hints Overlay

    enum Hints {
        static let overlayTitle = String(localized: "hint.overlay.title", defaultValue: "Keyboard Shortcuts")
        static let commandPalette = String(localized: "hint.commandPalette", defaultValue: "Command Palette")
        static let splitHorizontal = String(localized: "hint.splitHorizontal", defaultValue: "Split Horizontal")
        static let splitVertical = String(localized: "hint.splitVertical", defaultValue: "Split Vertical")
        static let closePane = String(localized: "hint.closePane", defaultValue: "Close Pane")
        static let focusPrevious = String(localized: "hint.focusPrevious", defaultValue: "Focus Previous Pane")
        static let focusNext = String(localized: "hint.focusNext", defaultValue: "Focus Next Pane")
        static let newWorkspace = String(localized: "hint.newWorkspace", defaultValue: "New Workspace")
        static let toggleMinimalMode = String(localized: "hint.toggleMinimalMode", defaultValue: "Toggle Minimal Mode")
        static let toggleFind = String(localized: "hint.toggleFind", defaultValue: "Toggle Find")
        static let toggleAIChat = String(localized: "hint.toggleAIChat", defaultValue: "Toggle AI Chat")
        static let toggleSidebar = String(localized: "hint.toggleSidebar", defaultValue: "Toggle Sidebar")
        static let zoomFocusedPane = String(localized: "hint.zoomFocusedPane", defaultValue: "Zoom Focused Pane")
    }

    // MARK: - Keyboard Actions

    enum KeyboardActions {
        static let newWorkspace = String(localized: "keyboard.action.newWorkspace", defaultValue: "New Workspace")
        static let closeWorkspace = String(localized: "keyboard.action.closeWorkspace", defaultValue: "Close Workspace")
        static let renameWorkspace = String(localized: "keyboard.action.renameWorkspace", defaultValue: "Rename Workspace")
        static let nextWorkspace = String(localized: "keyboard.action.nextWorkspace", defaultValue: "Next Workspace")
        static let prevWorkspace = String(localized: "keyboard.action.prevWorkspace", defaultValue: "Previous Workspace")
        static let splitRight = String(localized: "keyboard.action.splitRight", defaultValue: "Split Right")
        static let splitDown = String(localized: "keyboard.action.splitDown", defaultValue: "Split Down")
        static let toggleSplitZoom = String(localized: "keyboard.action.toggleSplitZoom", defaultValue: "Toggle Pane Zoom")
        static let focusLeft = String(localized: "keyboard.action.focusLeft", defaultValue: "Focus Pane Left")
        static let focusRight = String(localized: "keyboard.action.focusRight", defaultValue: "Focus Pane Right")
        static let focusUp = String(localized: "keyboard.action.focusUp", defaultValue: "Focus Pane Up")
        static let focusDown = String(localized: "keyboard.action.focusDown", defaultValue: "Focus Pane Down")
        static let toggleSidebar = String(localized: "keyboard.action.toggleSidebar", defaultValue: "Toggle Sidebar")
        static let newWindow = String(localized: "keyboard.action.newWindow", defaultValue: "New Window")
        static let closeWindow = String(localized: "keyboard.action.closeWindow", defaultValue: "Close Window")
        static let showNotifications = String(localized: "keyboard.action.showNotifications", defaultValue: "Show Notifications")
        static let jumpToUnread = String(localized: "keyboard.action.jumpToUnread", defaultValue: "Jump to Unread")
        static let equalizeSplits = String(localized: "keyboard.action.equalizeSplits", defaultValue: "Equalize Splits")
        static let openBrowser = String(localized: "keyboard.action.openBrowser", defaultValue: "Open Browser")
        static let toggleBrowserDevTools = String(localized: "keyboard.action.toggleBrowserDevTools", defaultValue: "Toggle Browser Dev Tools")
        static let showBrowserConsole = String(localized: "keyboard.action.showBrowserConsole", defaultValue: "Show Browser Console")
        static let nextSurface = String(localized: "keyboard.action.nextSurface", defaultValue: "Next Surface")
        static let prevSurface = String(localized: "keyboard.action.prevSurface", defaultValue: "Previous Surface")
        static let selectWorkspaceByNumber = String(localized: "keyboard.action.selectWorkspaceByNumber", defaultValue: "Select Workspace by Number")
        static let selectSurfaceByNumber = String(localized: "keyboard.action.selectSurfaceByNumber", defaultValue: "Select Surface by Number")
        static let triggerFlash = String(localized: "keyboard.action.triggerFlash", defaultValue: "Trigger Pane Flash")
        static let openFolder = String(localized: "keyboard.action.openFolder", defaultValue: "Open Folder")
        static let sendFeedback = String(localized: "keyboard.action.sendFeedback", defaultValue: "Send Feedback")
        static let splitBrowserRight = String(localized: "keyboard.action.splitBrowserRight", defaultValue: "Split Browser Right")
        static let splitBrowserDown = String(localized: "keyboard.action.splitBrowserDown", defaultValue: "Split Browser Down")
        static let renameTab = String(localized: "keyboard.action.renameTab", defaultValue: "Rename Tab")
        static let toggleTerminalCopyMode = String(localized: "keyboard.action.toggleTerminalCopyMode", defaultValue: "Toggle Terminal Copy Mode")
        static let categoryWorkspaces = String(localized: "keyboard.category.workspaces", defaultValue: "Workspaces")
        static let categoryPanels = String(localized: "keyboard.category.panels", defaultValue: "Panels")
        static let categoryApp = String(localized: "keyboard.category.app", defaultValue: "App")
        static let categoryBrowser = String(localized: "keyboard.category.browser", defaultValue: "Browser")
        static let conflictMessage = String(localized: "keyboard.conflict.message", defaultValue: "Conflict detected. Choose a different shortcut.")
    }

    // MARK: - Alerting Channels

    enum AlertChannels {
        static let slackTitle = String(localized: "alerting.channel.slack.title", defaultValue: "Slack")
        static let telegramTitle = String(localized: "alerting.channel.telegram.title", defaultValue: "Telegram")
        static let discordTitle = String(localized: "alerting.channel.discord.title", defaultValue: "Discord")
        static let webhookTitle = String(localized: "alerting.channel.webhook.title", defaultValue: "Webhook")
        static let emailTitle = String(localized: "alerting.channel.email.title", defaultValue: "Email")
        static let slackWebhookPlaceholder = String(localized: "alerting.channel.slack.webhookPlaceholder", defaultValue: "Slack webhook URL")
        static let telegramBotTokenPlaceholder = String(localized: "alerting.channel.telegram.botTokenPlaceholder", defaultValue: "Bot token")
        static let telegramChatIDPlaceholder = String(localized: "alerting.channel.telegram.chatIDPlaceholder", defaultValue: "Chat ID")
        static let discordWebhookPlaceholder = String(localized: "alerting.channel.discord.webhookPlaceholder", defaultValue: "Discord webhook URL")
        static let webhookURLPlaceholder = String(localized: "alerting.channel.webhook.urlPlaceholder", defaultValue: "Webhook URL")
        static let testButton = String(localized: "alerting.channel.test.button", defaultValue: "Test Channel")
        static let saveButton = String(localized: "alerting.channel.save.button", defaultValue: "Save Channel")
        static let deleteButton = String(localized: "alerting.channel.delete.button", defaultValue: "Delete Channel")
        static let enabledToggle = String(localized: "alerting.channel.enabled.toggle", defaultValue: "Enabled")
        static let testSuccessMessage = String(localized: "alerting.channel.test.success", defaultValue: "Test notification sent successfully")
        static let testFailureMessage = String(localized: "alerting.channel.test.failure", defaultValue: "Failed to send test notification")
        static let credentialsSaved = String(localized: "alerting.channel.credentials.saved", defaultValue: "Credentials saved")
        static let credentialsRequired = String(localized: "alerting.channel.credentials.required", defaultValue: "Credentials required")
        static let noChannelsTitle = String(localized: "alerting.noChannels.title", defaultValue: "No channels configured")
        static let noChannelsMessage = String(localized: "alerting.noChannels.message", defaultValue: "Add a channel to receive alert notifications outside of Namu")
        static let addChannelButton = String(localized: "alerting.addChannel.button", defaultValue: "Add Channel")
        static let channelTypeLabel = String(localized: "alerting.channel.type.label", defaultValue: "Channel Type")
        static let channelNameLabel = String(localized: "alerting.channel.name.label", defaultValue: "Channel Name")
        static let channelNamePlaceholder = String(localized: "alerting.channel.name.placeholder", defaultValue: "My Channel")
    }

    // MARK: - Window

    enum Window {
        static let newWindowTitle = String(localized: "window.new.title", defaultValue: "New Window")
        static let closeWindowTitle = String(localized: "window.close.title", defaultValue: "Close Window")
        static let moveToWindowTitle = String(localized: "window.moveTo.title", defaultValue: "Move to Window")
        static let windowTitle = String(localized: "window.title", defaultValue: "Namu")
        static let minimizeTooltip = String(localized: "window.minimize.tooltip", defaultValue: "Minimize")
        static let maximizeTooltip = String(localized: "window.maximize.tooltip", defaultValue: "Maximize")
        static let fullscreenTooltip = String(localized: "window.fullscreen.tooltip", defaultValue: "Enter Full Screen")
        static let dragHandleTooltip = String(localized: "window.dragHandle.tooltip", defaultValue: "Drag to move window")
        static let resizeHandleTooltip = String(localized: "window.resizeHandle.tooltip", defaultValue: "Drag to resize")
        static let sidebarResizeTooltip = String(localized: "window.sidebarResize.tooltip", defaultValue: "Drag to resize sidebar")
        static let sidebarResetTooltip = String(localized: "window.sidebarReset.tooltip", defaultValue: "Double-click to reset sidebar width")
    }

    // MARK: - Ports / Remote

    enum Ports {
        static let openPortLabel = String(localized: "ports.open.label", defaultValue: "Open port")
        static let portForwardedLabel = String(localized: "ports.forwarded.label", defaultValue: "Forwarded")
        static let portLocalLabel = String(localized: "ports.local.label", defaultValue: "Local")
        static let portRemoteLabel = String(localized: "ports.remote.label", defaultValue: "Remote")
        static let openInBrowserTooltip = String(localized: "ports.openInBrowser.tooltip", defaultValue: "Open in browser")
        static let copyPortTooltip = String(localized: "ports.copy.tooltip", defaultValue: "Copy port URL")
        static let forwardPortTooltip = String(localized: "ports.forward.tooltip", defaultValue: "Forward port")
        static let stopForwardingTooltip = String(localized: "ports.stopForwarding.tooltip", defaultValue: "Stop forwarding")
    }

    // MARK: - Git / VCS

    enum Git {
        static let branchLabel = String(localized: "git.branch.label", defaultValue: "Branch")
        static let dirtyIndicator = String(localized: "git.dirty.indicator", defaultValue: "Uncommitted changes")
        static let cleanIndicator = String(localized: "git.clean.indicator", defaultValue: "Working tree clean")
        static let prStateOpen = String(localized: "git.pr.state.open", defaultValue: "Open")
        static let prStateMerged = String(localized: "git.pr.state.merged", defaultValue: "Merged")
        static let prStateClosed = String(localized: "git.pr.state.closed", defaultValue: "Closed")
        static let prChecksPassingLabel = String(localized: "git.pr.checks.passing", defaultValue: "Checks passing")
        static let prChecksFailingLabel = String(localized: "git.pr.checks.failing", defaultValue: "Checks failing")
        static let prChecksPendingLabel = String(localized: "git.pr.checks.pending", defaultValue: "Checks pending")
        static let fetchTooltip = String(localized: "git.fetch.tooltip", defaultValue: "Fetch latest")
        static let pullTooltip = String(localized: "git.pull.tooltip", defaultValue: "Pull changes")
        static let pushTooltip = String(localized: "git.push.tooltip", defaultValue: "Push commits")
        static let commitTooltip = String(localized: "git.commit.tooltip", defaultValue: "Commit changes")
        static let statusLabel = String(localized: "git.status.label", defaultValue: "Status")
        static let noRepoMessage = String(localized: "git.noRepo.message", defaultValue: "Not a git repository")
    }

    // MARK: - Shell States

    enum ShellState {
        static let idleLabel = String(localized: "shell.state.idle", defaultValue: "Idle")
        static let promptLabel = String(localized: "shell.state.prompt", defaultValue: "Prompt")
        static let runningLabel = String(localized: "shell.state.running", defaultValue: "Running")
        static let commandInputLabel = String(localized: "shell.state.commandInput", defaultValue: "Typing command")
        static let unknownLabel = String(localized: "shell.state.unknown", defaultValue: "Unknown")
        static let idleAccessibility = String(localized: "shell.state.idle.accessibility", defaultValue: "Shell is idle")
        static let promptAccessibility = String(localized: "shell.state.prompt.accessibility", defaultValue: "Shell is at prompt")
        static let runningAccessibility = String(localized: "shell.state.running.accessibility", defaultValue: "Shell is running a command")
        static let commandInputAccessibility = String(localized: "shell.state.commandInput.accessibility", defaultValue: "Shell is awaiting command input")
    }

    // MARK: - Markdown Viewer

    enum Markdown {
        static let fileUnavailableTitle = String(localized: "markdown.fileUnavailable.title", defaultValue: "File Unavailable")
        static let fileUnavailableMessage = String(localized: "markdown.fileUnavailable.message", defaultValue: "The file could not be loaded. It may have been moved or deleted.")
        static let retryButton = String(localized: "markdown.retry.button", defaultValue: "Retry")
        static let openExternallyButton = String(localized: "markdown.openExternally.button", defaultValue: "Open in Editor")
        static let copyPathTooltip = String(localized: "markdown.copyPath.tooltip", defaultValue: "Copy file path")
        static let refreshTooltip = String(localized: "markdown.refresh.tooltip", defaultValue: "Refresh file")
        static let renderingError = String(localized: "markdown.rendering.error", defaultValue: "Unable to render Markdown")
        static let emptyFile = String(localized: "markdown.emptyFile", defaultValue: "Empty file")
        static let loadingMessage = String(localized: "markdown.loading.message", defaultValue: "Loading…")
    }

    // MARK: - Accessibility

    enum Accessibility {
        static let mainContentArea = String(localized: "accessibility.mainContent", defaultValue: "Main content area")
        static let sidebarArea = String(localized: "accessibility.sidebar", defaultValue: "Sidebar")
        static let workspaceContent = String(localized: "accessibility.workspaceContent", defaultValue: "Workspace content")
        static let terminalPane = String(localized: "accessibility.terminalPane", defaultValue: "Terminal pane")
        static let browserPane = String(localized: "accessibility.browserPane", defaultValue: "Browser pane")
        static let splitHandle = String(localized: "accessibility.splitHandle", defaultValue: "Split resize handle")
        static let tabBar = String(localized: "accessibility.tabBar", defaultValue: "Tab bar")
        static let statusBar = String(localized: "accessibility.statusBar", defaultValue: "Status bar")
        static let toolbarSearch = String(localized: "accessibility.toolbarSearch", defaultValue: "Search")
        static let progressIndicator = String(localized: "accessibility.progress", defaultValue: "Progress")
        static let loadingSpinner = String(localized: "accessibility.loading", defaultValue: "Loading")
        static let closeButton = String(localized: "accessibility.closeButton", defaultValue: "Close")
        static let expandButton = String(localized: "accessibility.expandButton", defaultValue: "Expand")
        static let collapseButton = String(localized: "accessibility.collapseButton", defaultValue: "Collapse")
        static let sortAscending = String(localized: "accessibility.sort.ascending", defaultValue: "Sorted ascending")
        static let sortDescending = String(localized: "accessibility.sort.descending", defaultValue: "Sorted descending")
        static let selected = String(localized: "accessibility.selected", defaultValue: "Selected")
        static let notSelected = String(localized: "accessibility.notSelected", defaultValue: "Not selected")
        static let required = String(localized: "accessibility.required", defaultValue: "Required field")
    }
}
// swiftlint:enable file_length type_body_length
